In [ ]:
#Peoblem 1: Array Creation
import numpy as np
#1
arr1 = np.empty((2, 2))
print(arr1)
print(" ")

#2
arr2 = np.ones((4,2))
print(arr2)
print(" ")

#3
arr3 = np.full((2, 3), 5)
print(arr3)
print(" ")

#4
arr4 = np.zeros_like(arr3)
print(arr4)
print(" ")

#5
arr5 = np.ones_like(arr3)
print(arr5)
print(" ")

#6
new_list = [1,2,3,4]
arr6 = np.array(new_list)
print(arr6)
print(" ")

[[4.99751333e-310 0.00000000e+000]
 [6.80872169e-310 6.80868470e-310]]
 
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
 
[[5 5 5]
 [5 5 5]]
 
[[0 0 0]
 [0 0 0]]
 
[[1 1 1]
 [1 1 1]]
 
[1 2 3 4]
 


In [ ]:
#Problem - 2: Array Manipulation
import numpy as np
#1
arr1 = np.arange(10, 50)
print(arr1)
print(" ")

#2
arr2 = np.arange(0, 9)
arr2 = arr2.reshape(3, 3)
print(arr2)
print(" ")

#3
arr3 = np.eye(3,3)
print(arr3)
print(" ")

#4
arr4 = np.random.random(30)
mean = np.mean(arr4)
print("The mean of", arr4, "is", mean)
print(" ")

#5
arr5 = np.random.rand(10,10)
min = np.min(arr5)
max = np.max(arr5)
print("The minimum value of", arr5, "is", min)
print("The maximum value of", arr5, "is", max)
print(" ")

#6
arr6 = np.zeros(10)
arr6[4] = 1
print(arr6)
print(" ")

#7
arr7 =[1,2,0,0,4,0]
reversed_arr7 = arr7[::-1]
print(reversed_arr7)
print(" ")

#8
arr8 = np.zeros((3,3))
arr8[0, :] = 1
arr8[-1, :] = 1
arr8[:, 0] = 1
arr8[:, -1] = 1
print(arr8)
print(" ")

#9
arr9 = np.zeros((8,8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print(arr9)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
The mean of [0.14233276 0.83651239 0.83494279 0.73249103 0.88243587 0.35738755
 0.526491   0.93518787 0.62398997 0.58670971 0.22343847 0.41065377
 0.19754214 0.0515432  0.8068448  0.11639    0.82586974 0.81160742
 0.27354077 0.40946587 0.9746786  0.66954405 0.76842194 0.24471757
 0.11838268 0.48186915 0.08524988 0.92753757 0.98559725 0.13274565] is 0.5324707151906952
 
The minimum value of [[0.23283577 0.11725935 0.97774783 0.07008336 0.45385347 0.93808183
  0.18971319 0.41449686 0.65386663 0.98018013]
 [0.86144718 0.42376602 0.26736599 0.39960325 0.13369731 0.74144688
  0.30280767 0.17511008 0.87782895 0.37903115]
 [0.52811683 0.75094025 0.8584646  0.82177767 0.57894003 0.83855036
  0.15373666 0.07675091 0.87150963 0.4074729 ]
 [0.61481945 0.08773983 0.94780135 0.98048212 0.34686389 0.88866892


In [ ]:
#Problem - 3: Array Operations
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1
print(np.add(x, y))
print(np.add(v, w))
print(" ")

#2
print(np.subtract(x, y))
print(np.subtract(v, w))
print(" ")

#3
print(np.multiply(x,2))
print(" ")

#4
print(np.square(y))
print(" ")

#5
print("v.w =", np.dot(v, w))
print("x.v =", np.dot(x, v))
print("x.y =", np.dot(x, y))
print(" ")

#6
xy_concatenated = np.concatenate((x, y), axis=0)
vw_concatenated = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenated x and y along rows:")
print(xy_concatenated)
print("Concatenated v and w along columns:")
print(vw_concatenated)

#7
print(np.concatenate(x, v))


[[ 6  8]
 [10 13]]
[20 22]
 
[[-4 -4]
 [-4 -3]]
[-2 -2]
 
[[ 2  4]
 [ 6 10]]
 
[[25 36]
 [49 64]]
 
v.w = 219
x.v = [29 77]
x.y = [[19 22]
 [50 58]]
 
Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


TypeError: only integer scalar arrays can be converted to a scalar index

The error occurs because np.concatenate expects a list of arrays as its first argument, followed by an optional axis argument. Here, the  provided x (an array) as the first argument and v (another array) as the second. NumPy is mistakenly interpreting v as the axis argument, which should be an integer, not an array.

In [2]:
#Problem - 4: Matrix Operations
import numpy as np
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Verify A * A^-1 = I
inv_A = np.linalg.inv(A)
identity_matrix = np.eye(2)
lhs_1 = np.dot(A, inv_A)

print("1. Verifying A * A^-1 = I")
print("A * A^-1 = \n", lhs_1)
print("Identity Matrix = \n", identity_matrix)

if np.allclose(lhs_1, identity_matrix):
    print("Result: A * A^-1 = I (Proven)\n")
else:
    print("Result: A * A^-1 ≠ I\n")

# 2. Verify AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)

print("2. Verifying AB ≠ BA")
print("AB = \n", AB)
print("BA = \n", BA)

if np.array_equal(AB, BA):
    print("Result: AB = BA (Unexpected)\n")
else:
    print("Result: AB ≠ BA (Proven)\n")

# 3. Verify (AB)^T = B^T * A^T
AB_T = np.transpose(np.dot(A, B))
BT_AT = np.dot(np.transpose(B), np.transpose(A))

print("3. Verifying (AB)^T = B^T * A^T")
print("(AB)^T = \n", AB_T)
print("B^T * A^T = \n", BT_AT)

if np.allclose(AB_T, BT_AT):
    print("Result: (AB)^T = B^T * A^T (Proven)\n")
else:
    print("Result: (AB)^T ≠ B^T * A^T\n")


1. Verifying A * A^-1 = I
A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix = 
 [[1. 0.]
 [0. 1.]]
Result: A * A^-1 = I (Proven)

2. Verifying AB ≠ BA
AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
Result: AB ≠ BA (Proven)

3. Verifying (AB)^T = B^T * A^T
(AB)^T = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]
Result: (AB)^T = B^T * A^T (Proven)

